import Finance from './Finance'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { commerceRequest as api, type Client, type ClientInput } from '../api/commerce'
import Contracts from './Contracts'
import Actions from './Actions'
const empty: ClientInput = { firstName: '', lastName: '', company: '', email: '', phone: '', notes: '' }
export default function Clients({ initialId }: { initialId?: number }) {
  const [rows, setRows] = useState<Client[]>([]), [detail, setDetail] = useState<Client | null>(null)
  const [input, setInput] = useState<ClientInput | null>(null), [editing, setEditing] = useState<number | undefined>()
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(''), [history, setHistory] = useState(false)
  const generation = useRef(0)
  async function refresh() { const n = ++generation.current; setLoading(true)
    try { const r = await api<Client[]>('clients'); if(n === generation.current) setRows(r) } catch(e) { if(n === generation.current) setError(e instanceof Error ? e.message : 'Erreur API.') } finally { if(n === generation.current) setLoading(false) }
  }
  async function view(id: number) { setError(''); setHistory(false); try { setDetail(await api<Client>(`clients/${id}`)) } catch(e) { setError(e instanceof Error ? e.message : 'Erreur API.') } }
  useEffect(() => { void refresh(); if(initialId) void view(initialId); return () => { generation.current++ } }, [initialId])
  function open(c?: Client) { setEditing(c?.id); setInput(c ? { firstName: c.firstName, lastName: c.lastName, company: c.company, email: c.email, phone: c.phone, notes: c.notes } : { ...empty }); setError(''); setSuccess('') }
  async function mutate(operation: () => Promise<unknown>, message: string) { if(busy) return; setBusy(true); setError(''); setSuccess(''); try { await operation(); setSuccess(message); await refresh() } catch(e) { setError(e instanceof Error ? e.message : 'Erreur API.') } finally { setBusy(false) } }
  function save(e: FormEvent) { e.preventDefault(); void mutate(async () => { const c = await api<Client>(`clients${editing ? `/${editing}` : ''}`, editing ? 'PUT' : 'POST', input); setInput(null); if(detail?.id === c.id) await view(c.id) }, 'Client enregistré.') }
  return <section className="prospects-card"><div className="prospects-toolbar"><h2>Clients</h2><button className="button button-primary" disabled={busy || !!input} onClick={() => open()}>Nouveau client</button></div>
    {success && <p className="notice notice-success" role="status">{success}</p>}{error && <p className="notice notice-error" role="alert">{error} <button className="button" disabled={busy || loading} onClick={() => void refresh()}>Réessayer</button></p>}
    {input && <form className="prospect-form" onSubmit={save}><h3>{editing ? 'Modifier le client' : 'Nouveau client'}</h3><fieldset disabled={busy}><div className="form-grid">{([['firstName','Prénom'],['lastName','Nom'],['company','Société'],['email','Email'],['phone','Téléphone']] as const).map(([k,v]) => <label key={k}>{v}{['firstName','lastName'].includes(k) && ' *'}<input autoFocus={k === 'firstName'} required={['firstName','lastName'].includes(k)} type={k === 'email' ? 'email' : k === 'phone' ? 'tel' : 'text'} value={input[k] ?? ''} onChange={e => setInput({ ...input, [k]: e.target.value })}/></label>)}<label className="form-notes">Notes<textarea value={input.notes ?? ''} onChange={e => setInput({ ...input, notes: e.target.value })}/></label></div><div className="form-actions"><button className="button button-primary">Enregistrer</button><button className="button" type="button" onClick={() => setInput(null)}>Annuler</button></div></fieldset></form>}
    {loading ? <p role="status">Chargement des clients…</p> : !error && !rows.length ? <p className="empty-list">Aucun client.</p> : <div className="table-scroll"><table className="prospects-table"><thead><tr>{['Identité','Société','Email','Téléphone','Contrats','Actions'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map(c => <tr key={c.id}><td>{c.firstName} {c.lastName}</td><td>{c.company || '—'}</td><td>{c.email || '—'}</td><td>{c.phone || '—'}</td><td>{c._count.contracts}</td><td><div className="row-actions"><button className="button" disabled={busy} onClick={() => void view(c.id)}>Consulter</button><button className="button" disabled={busy || !!input} onClick={() => open(c)}>Modifier</button><button className="button button-danger" disabled={busy || !!input || !!c.sourceProspectId || c._count.contracts > 0} onClick={() => { if(window.confirm(`Supprimer ${c.firstName} ${c.lastName} ?`)) void mutate(async () => { await api(`clients/${c.id}`, 'DELETE'); if(detail?.id === c.id) setDetail(null) }, 'Client supprimé.') }}>Supprimer</button></div></td></tr>)}</tbody></table></div>}
    {detail && <section className="action-group"><div className="prospects-toolbar"><h3>Fiche : {detail.firstName} {detail.lastName}</h3><button className="button" onClick={() => setDetail(null)}>Fermer la fiche</button></div><p>{detail.company || '—'} · {detail.email || '—'} · {detail.phone || '—'}</p><p className="action-description">{detail.notes}</p>{detail.sourceProspect && <><p>Prospect d’origine : {detail.sourceProspect.firstName} {detail.sourceProspect.lastName} (#{detail.sourceProspect.id})</p><button className="button" onClick={() => setHistory(v => !v)}>Historique commercial du prospect</button>{history && <Actions prospect={detail.sourceProspect}/>}</>}<Finance key={'q'+detail.id} kind='quotes' clientId={detail.id}/><Finance key={'i'+detail.id} kind='invoices' clientId={detail.id}/><Contracts key={detail.id} clientId={detail.id} onChange={() => void refresh()}/></section>}
  </section>
}
