import { useEffect, useRef, useState, type FormEvent } from 'react'
import { commerceRequest as api, money, eurosToCents, type Client, type Contract } from '../api/commerce'
type Line = { description: string; quantity: string; unitPriceCents: number; vatRateBasisPoints: number }
type Payment = { id: number; invoiceId: number; amountCents: number; paidAt: string; method: string; reference: string | null; notes: string | null }
type Document = { id: number; clientId: number; contractId: number | null; reference: string; title: string; description?: string | null; status: string; issueDate: string; validUntil?: string | null; dueDate?: string; vatExemptionMention: string | null; totalExclTaxCents: number; vatCents: number; totalInclTaxCents: number; vatRateBasisPoints?: number; lines?: Line[]; payments?: Payment[]; paidCents?: number; remainingCents?: number; paymentStatus?: string; overdue?: boolean; client?: Client }
type Form = { clientId: number; contractId: number | null; reference: string; title: string; description: string; status: string; issueDate: string; validUntil: string; dueDate: string; vatExemptionMention: string; amount: string; vatRateBasisPoints: number; lines: (Line & { price: string })[] }
const today = () => { const parts = new Intl.DateTimeFormat('en', { timeZone: 'Europe/Paris', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const get = (type: string) => parts.find(p => p.type === type)!.value; return `${get('year')}-${get('month')}-${get('day')}` }
const euro = (c: number) => `${Math.floor(c/100)}.${String(c%100).padStart(2,'0')}`
const labels: Record<string,string> = { DRAFT: 'Brouillon', SENT: 'Envoyé', ACCEPTED: 'Accepté', REJECTED: 'Refusé', EXPIRED: 'Expiré', ISSUED: 'Émise', CANCELLED: 'Annulée', UNPAID: 'Non réglée', PARTIAL: 'Partiellement réglée', PAID: 'Réglée' }
const methods: Record<string,string> = { BANK_TRANSFER: 'Virement', CARD: 'Carte', CASH: 'Espèces', CHECK: 'Chèque', OTHER: 'Autre' }
const newLine = () => ({ description: '', quantity: '1', unitPriceCents: 0, vatRateBasisPoints: 0, price: '0.00' })
// Exact integer preview: half up per line, then VAT on the rounded HT.
function preview(form: Form, quote: boolean) {
  const lines = quote ? form.lines : [{ quantity: '1', price: form.amount, vatRateBasisPoints: form.vatRateBasisPoints }]
  let ht = 0n, tax = 0n
  for (const l of lines) {
    if (!/^\d{1,8}(?:\.\d{1,4})?$/.test(l.quantity)) throw new Error('Quantité invalide')
    const [whole,fraction = ''] = l.quantity.split('.'), quantity = BigInt(whole)*10000n+BigInt(fraction.padEnd(4,'0'))
    const lineHt = (quantity*BigInt(eurosToCents(l.price))+5000n)/10000n
    ht += lineHt; tax += (lineHt*BigInt(l.vatRateBasisPoints)+5000n)/10000n
  }
  return `${money(Number(ht))} HT · ${money(Number(tax))} TVA · ${money(Number(ht+tax))} TTC (prévisionnel)`
}
export default function Finance({ kind, clientId, contractId }: { kind: 'quotes' | 'invoices'; clientId?: number; contractId?: number }) {
  const quote = kind === 'quotes', statuses = quote ? ['DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED'] : ['DRAFT','ISSUED','CANCELLED']
  const [rows,setRows] = useState<Document[]>([]), [clients,setClients] = useState<Client[]>([]), [contracts,setContracts] = useState<Contract[]>([])
  const [form,setForm] = useState<Form | null>(null), [editing,setEditing] = useState<number>(), [detail,setDetail] = useState<Document | null>(null)
  const [filterClient,setFilterClient] = useState(String(clientId ?? '')), [filterStatus,setFilterStatus] = useState(''), [search,setSearch] = useState('')
  const [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(''), [success,setSuccess] = useState('')
  const [payment,setPayment] = useState({ id: 0, amount: '', paidAt: today(), method: 'BANK_TRANSFER', reference: '', notes: '' })
  const generation = useRef(0)
  async function refresh() {
    const n = ++generation.current; setLoading(true)
    try {
      const q = new URLSearchParams(); if(filterClient) q.set('clientId',filterClient); if(contractId) q.set('contractId',String(contractId)); if(filterStatus) q.set('status',filterStatus); if(search) q.set('search',search)
      const [r,c,k] = await Promise.all([api<Document[]>(`${kind}?${q}`),api<Client[]>('clients'),api<Contract[]>('contracts')])
      if(n === generation.current) { setRows(r); setClients(c); setContracts(k) }
    } catch(e) { if(n === generation.current) setError(e instanceof Error ? e.message : 'Erreur API.') }
    finally { if(n === generation.current) setLoading(false) }
  }
  useEffect(() => { setError(''); setDetail(null); setForm(null); void refresh(); return () => { generation.current++ } }, [kind,filterClient,filterStatus,search,contractId])
  function open(row?: Document) {
    setEditing(row?.id); setError(''); setSuccess('')
    setForm({ clientId: row?.clientId ?? clientId ?? clients[0]?.id ?? 0, contractId: row?.contractId ?? contractId ?? null, reference: row?.reference ?? '', title: row?.title ?? '', description: row?.description ?? '', status: row?.status ?? 'DRAFT', issueDate: row?.issueDate.slice(0,10) ?? today(), validUntil: row?.validUntil?.slice(0,10) ?? '', dueDate: row?.dueDate?.slice(0,10) ?? today(), vatExemptionMention: row?.vatExemptionMention ?? '', amount: euro(row?.totalExclTaxCents ?? 0), vatRateBasisPoints: row?.vatRateBasisPoints ?? 0, lines: row?.lines?.map(l => ({ ...l, price: euro(l.unitPriceCents) })) ?? [newLine()] })
  }
  function payload(f: Form) {
    const common = { clientId: f.clientId, contractId: f.contractId, reference: f.reference, title: f.title, status: f.status, issueDate: f.issueDate, vatExemptionMention: f.vatExemptionMention }
    return quote ? { ...common, description: f.description, validUntil: f.validUntil || null, lines: f.lines.map(l => ({ description: l.description, quantity: l.quantity, unitPriceCents: eurosToCents(l.price), vatRateBasisPoints: l.vatRateBasisPoints })) } : { ...common, dueDate: f.dueDate, totalExclTaxCents: eurosToCents(f.amount), vatRateBasisPoints: f.vatRateBasisPoints }
  }
  async function view(id: number) { const row = await api<Document>(`${kind}/${id}`); setDetail(row); setPayment({ id:0, amount:'', paidAt:today(), method:'BANK_TRANSFER', reference:'', notes:'' }); return row }
  async function mutate(operation: () => Promise<unknown>, message = 'Enregistré.') {
    if(busy) return; setBusy(true); setError(''); setSuccess('')
    try { await operation(); await refresh(); setSuccess(message) } catch(e) { setError(e instanceof Error ? e.message : 'Erreur API.') } finally { setBusy(false) }
  }
  function save(e: FormEvent) { e.preventDefault(); if(!form) return; void mutate(async () => { const r = await api<Document>(`${kind}${editing ? `/${editing}` : ''}`,editing ? 'PUT' : 'POST',payload(form)); setForm(null); await view(r.id) }) }
  async function transition(row: Document, next: string) {
    const common = { clientId: row.clientId, contractId: row.contractId, reference: row.reference, title: row.title, status: next, issueDate: row.issueDate.slice(0,10), vatExemptionMention: row.vatExemptionMention }
    const body = quote ? { ...common, description: row.description, validUntil: row.validUntil?.slice(0,10) ?? null, lines: row.lines?.map(l => ({ description: l.description, quantity: l.quantity, unitPriceCents: l.unitPriceCents, vatRateBasisPoints: l.vatRateBasisPoints })) } : { ...common, dueDate: row.dueDate?.slice(0,10), totalExclTaxCents: row.totalExclTaxCents, vatRateBasisPoints: row.vatRateBasisPoints }
    await api(`${kind}/${row.id}`,'PUT',body); if(detail?.id === row.id) await view(row.id)
  }
  let estimate = ''; if(form) { try { estimate = preview(form,quote) } catch { estimate = 'Complétez les montants et quantités pour calculer les totaux.' } }
  return <section className="prospects-card"><div className="prospects-toolbar"><h2>{quote ? 'Devis' : 'Factures'}</h2><button className="button button-primary" disabled={busy || loading || !!form || !clients.length} onClick={() => open()}>{quote ? 'Nouveau devis' : 'Nouvelle facture'}</button></div>
    {!quote && <p className="form-hint">Suivi interne uniquement. Aucun document fiscal officiel n’est émis.</p>}
    {error && <p className="notice notice-error" role="alert">{error} <button className="button" onClick={() => { setError(''); void refresh() }}>Réessayer</button></p>}{success && <p className="notice notice-success" role="status">{success}</p>}
    <div className="form-grid">{!clientId && <label>Client<select value={filterClient} onChange={e => setFilterClient(e.target.value)}><option value="">Tous</option>{clients.map(c => <option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label>}<label>Statut<select value={filterStatus} onChange={e => setFilterStatus(e.target.value)}><option value="">Tous</option>{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Recherche<input value={search} onChange={e => setSearch(e.target.value)}/></label></div>
    {form && <form className="prospect-form" onSubmit={save}><h3>{editing ? 'Modifier' : 'Créer'} {quote ? 'le devis' : 'la facture'}</h3><fieldset disabled={busy}><div className="form-grid">
      <label>Client *<select required value={form.clientId || ''} onChange={e => setForm({ ...form, clientId: Number(e.target.value), contractId: null })}><option value="" disabled>Choisir</option>{clients.map(c => <option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label>
      <label>Contrat facultatif<select value={form.contractId ?? ''} onChange={e => setForm({ ...form, contractId: e.target.value ? Number(e.target.value) : null })}><option value="">Aucun</option>{contracts.filter(c => c.clientId === form.clientId).map(c => <option key={c.id} value={c.id}>{c.reference} — {c.title}</option>)}</select></label>
      <label>Référence (automatique si vide)<input maxLength={100} value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })}/></label><label>Titre *<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/></label>
      <label>Statut<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}>{statuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label>
      <label>Date *<input required type="date" value={form.issueDate} onChange={e => setForm({ ...form, issueDate: e.target.value })}/></label><label>{quote ? 'Validité' : 'Échéance *'}<input required={!quote} type="date" value={quote ? form.validUntil : form.dueDate} onChange={e => setForm({ ...form, [quote ? 'validUntil' : 'dueDate']: e.target.value })}/></label>
      {!quote && <><label>Montant HT en euros *<input required inputMode="decimal" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/></label><label>TVA<select value={form.vatRateBasisPoints} onChange={e => setForm({ ...form, vatRateBasisPoints: Number(e.target.value) })}><option value={0}>0 %</option><option value={2000}>20 %</option></select></label></>}
      {quote && <label>Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label>}
      <label>Mention TVA facultative<textarea value={form.vatExemptionMention} onChange={e => setForm({ ...form, vatExemptionMention: e.target.value })}/></label>
    </div>{quote && <><h4>Lignes</h4>{form.lines.map((l,i) => <div className="finance-line form-grid" key={i}>{(['description','quantity','price'] as const).map(k => <label key={k}>{k === 'description' ? 'Prestation *' : k === 'quantity' ? 'Quantité *' : 'Prix unitaire HT (€) *'}<input required inputMode={k === 'description' ? 'text' : 'decimal'} value={l[k]} onChange={e => setForm({ ...form, lines: form.lines.map((v,n) => n === i ? { ...v, [k]: e.target.value } : v) })}/></label>)}<label>TVA<select value={l.vatRateBasisPoints} onChange={e => setForm({ ...form, lines: form.lines.map((v,n) => n === i ? { ...v, vatRateBasisPoints: Number(e.target.value) } : v) })}><option value={0}>0 %</option><option value={2000}>20 %</option></select></label><button className="button button-danger" type="button" disabled={form.lines.length === 1} onClick={() => setForm({ ...form, lines: form.lines.filter((_,n) => n !== i) })}>Supprimer la ligne</button></div>)}<button className="button" type="button" disabled={form.lines.length >= 200} onClick={() => setForm({ ...form, lines: [...form.lines,newLine()] })}>Ajouter une ligne</button></>}
    <p role="status">{estimate}</p><div className="form-actions"><button className="button button-primary">Enregistrer</button><button className="button" type="button" onClick={() => setForm(null)}>Annuler</button></div></fieldset></form>}
    {loading ? <p role="status">Chargement…</p> : !rows.length ? <p className="empty-list">Aucun {quote ? 'devis' : 'enregistrement de facture'}.</p> : <div className="table-scroll"><table className="prospects-table"><thead><tr>{['Référence / titre','Client','Date','HT','TVA','TTC',...(!quote ? ['Encaissé TTC','Solde TTC','Échéance','Règlement'] : []),'Statut','Actions'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r => <tr key={r.id}><td><strong>{r.reference}</strong><p>{r.title}</p></td><td>{r.client?.firstName} {r.client?.lastName}</td><td>{r.issueDate.slice(0,10)}</td><td>{money(r.totalExclTaxCents)}</td><td>{money(r.vatCents)}{!quote && ` (${(r.vatRateBasisPoints ?? 0)/100} %)`}</td><td>{money(r.totalInclTaxCents)}</td>{!quote && <><td>{money(r.paidCents ?? 0)}</td><td>{money(r.remainingCents ?? 0)}</td><td>{r.dueDate?.slice(0,10)}{r.overdue && <p className="notice-error">En retard</p>}</td><td>{labels[r.paymentStatus ?? 'UNPAID']}</td></>}<td>{labels[r.status]}</td><td><div className="row-actions"><button className="button" disabled={busy} onClick={() => void mutate(() => view(r.id),'Fiche chargée.')}>Consulter</button><button className="button" disabled={busy || !!form || (quote ? r.status === 'ACCEPTED' : r.status !== 'DRAFT')} onClick={() => open(r)}>Modifier</button>
    {(quote && r.status !== 'ACCEPTED' ? statuses.filter(s => s !== r.status) : !quote && r.status === 'DRAFT' ? ['ISSUED'] : !quote && r.status === 'ISSUED' && !r.payments?.length ? ['CANCELLED'] : []).map(s => <button key={s} className="button" disabled={busy} onClick={() => { if(window.confirm(`Passer à « ${labels[s]} » ?`)) void mutate(() => transition(r,s)) }}>{labels[s]}</button>)}
    <button className="button button-danger" disabled={busy || (quote ? r.status === 'ACCEPTED' : r.status !== 'DRAFT' || !!r.payments?.length)} onClick={() => { if(window.confirm(`Supprimer ${r.reference} ?`)) void mutate(async () => { await api(`${kind}/${r.id}`,'DELETE'); if(detail?.id === r.id) setDetail(null) },'Supprimé.') }}>Supprimer</button></div></td></tr>)}</tbody></table></div>}
    {detail && <section className="action-group"><div className="prospects-toolbar"><h3>{detail.reference} — {detail.title}</h3><button className="button" onClick={() => setDetail(null)}>Fermer</button></div><p>{detail.description}</p><p>{detail.vatExemptionMention}</p><p>{money(detail.totalExclTaxCents)} HT · {money(detail.vatCents)} TVA · {money(detail.totalInclTaxCents)} TTC</p>{quote ? <>{detail.lines?.map((l,i) => <p key={i}>{l.description} · {l.quantity} × {money(l.unitPriceCents)} HT · TVA {l.vatRateBasisPoints/100} %</p>)}{detail.status === 'ACCEPTED' && <p>Devis verrouillé. Pour une révision, créez un nouveau devis avec une nouvelle référence.</p>}</> : <><p>Encaissé : {money(detail.paidCents ?? 0)} TTC · Restant : {money(detail.remainingCents ?? 0)} TTC</p><h4>Historique des règlements</h4>{!detail.payments?.length && <p>Aucun règlement.</p>}{detail.payments?.map(p => <div key={p.id} className="finance-line"><p>{p.paidAt.slice(0,10)} · {money(p.amountCents)} TTC · {methods[p.method]} · {p.reference} · {p.notes}</p><button className="button" disabled={busy} onClick={() => setPayment({ id:p.id, amount:euro(p.amountCents), paidAt:p.paidAt.slice(0,10), method:p.method, reference:p.reference ?? '', notes:p.notes ?? '' })}>Corriger</button> <button className="button button-danger" disabled={busy} onClick={() => { if(window.confirm('Supprimer ce paiement erroné ?')) void mutate(async () => { await api(`payments/${p.id}`,'DELETE'); await view(detail.id) },'Paiement supprimé.') }}>Supprimer</button></div>)}
      {detail.status === 'ISSUED' && <form className="prospect-form" onSubmit={e => { e.preventDefault(); void mutate(async () => { await api(`payments${payment.id ? `/${payment.id}` : ''}`,payment.id ? 'PUT' : 'POST',{ invoiceId: detail.id, amountCents: eurosToCents(payment.amount), paidAt: payment.paidAt, method: payment.method, reference: payment.reference, notes: payment.notes }); setPayment({ id:0, amount:'', paidAt:today(), method:'BANK_TRANSFER', reference:'', notes:'' }); await view(detail.id) },'Paiement enregistré.') }}><h4>{payment.id ? 'Corriger le paiement' : 'Enregistrer un paiement'}</h4><fieldset disabled={busy}><div className="form-grid"><label>Montant TTC (€) *<input required inputMode="decimal" value={payment.amount} onChange={e => setPayment({ ...payment, amount:e.target.value })}/></label><label>Date *<input required type="date" value={payment.paidAt} onChange={e => setPayment({ ...payment, paidAt:e.target.value })}/></label><label>Mode<select value={payment.method} onChange={e => setPayment({ ...payment, method:e.target.value })}>{Object.entries(methods).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label>{(['reference','notes'] as const).map(k => <label key={k}>{k === 'notes' ? 'Notes' : 'Référence'}<input value={payment[k]} onChange={e => setPayment({ ...payment, [k]:e.target.value })}/></label>)}</div><button className="button button-primary">Enregistrer le règlement</button>{!!payment.id && <button className="button" type="button" onClick={() => setPayment({ ...payment,id:0,amount:'' })}>Annuler la correction</button>}</fieldset></form>}</> }</section>}
  </section>
}
