import { useEffect, useState } from 'react'
import { commerceRequest as api, eurosToCents, money, contractLabels } from '../api/commerce'
import { statusLabels } from '../api/prospects'
import { DateRangeFilter } from './ListTools'
type Month={month:string;prospectsCreated:number;clientsCreated:number;signedExclTaxCents:number;invoicedExclTaxCents:number;receivedInclTaxCents:number}
type Goal={month:string;monthlyExclTaxCents:number;invoicedExclTaxCents:number;achievementPercent:number|null;remainingExclTaxCents:number}
type Pipeline={prospects:{status:keyof typeof statusLabels;_count:number}[];contracts:{status:keyof typeof contractLabels;_count:number}[]}
const dateString=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
function preset(months:number){const now=new Date();return {from:dateString(new Date(now.getFullYear(),now.getMonth()-months+1,1)),to:dateString(now)}}
const metrics:Record<string,string>={prospectsCreated:'Prospects créés',prospectsCurrentlyContacted:'Cohorte actuellement contactée',prospectsCurrentlyQualified:'Cohorte actuellement qualifiée',cohortConverted:'Prospects de la cohorte convertis',conversionRate:'Conversion de la cohorte (%)',clientsCreated:'Clients créés',contractsSigned:'Contrats signés',signedExclTaxCents:'Contrats signés HT',sentQuotesExclTaxCents:'Devis actuellement envoyés HT',invoicedExclTaxCents:'Facturé HT',receivedInclTaxCents:'Encaissé TTC',actionsCompleted:'Actions effectuées',actionsCurrentlyOverdue:'Actions actuellement en retard'}
function Chart({title,values,monetary=false}:{title:string;values:{label:string;value:number}[];monetary?:boolean}) {
  const max=Math.max(1,...values.map(v=>v.value));
  return <section className="report-chart"><h3>{title}</h3>{!values.length||values.every(v=>v.value===0)?<p>Aucune donnée sur cette période.</p>:null}<div className="chart-bars" role="img" aria-label={title}>{values.map(v=><div className="chart-row" key={v.label}><span>{v.label}</span><div className="bar-track"><div className="bar-value" style={{width:`${v.value/max*100}%`}}/></div><strong>{monetary?money(v.value):v.value}</strong></div>)}</div></section>
}
export default function Reporting() {
  const [period,setPeriod]=useState(()=>preset(1)),[selection,setSelection]=useState('1'),[overview,setOverview]=useState<Record<string,number>|null>(null),[monthly,setMonthly]=useState<Month[]>([]),[pipeline,setPipeline]=useState<Pipeline|null>(null),[goal,setGoal]=useState<Goal|null>(null)
  const [amount,setAmount]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[saved,setSaved]=useState('')
  const query=new URLSearchParams({...period,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).toString()
  useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([api<Record<string,number>>('reports/overview?'+query),api<Month[]>('reports/monthly?'+query),api<Pipeline>('reports/pipeline?'+query),api<Goal>('reports/goal?'+new URLSearchParams({...preset(1),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}))]).then(([o,m,p,g])=>{if(active){setOverview(o);setMonthly(m);setPipeline(p);setGoal(g);setAmount((g.monthlyExclTaxCents/100).toFixed(2))}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query,revision])
  async function saveGoal(){setBusy(true);setError('');setSaved('');try {await api('reports/goal','PUT',{monthlyExclTaxCents:eurosToCents(amount)});setSaved('Objectif enregistré.');setRevision(r=>r+1)}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.')}finally{setBusy(false)}}
  return <section className="prospects-card"><div className="form-grid"><label>Période<select value={selection} onChange={e=>{setSelection(e.target.value);if(e.target.value!=='custom')setPeriod(preset(Number(e.target.value)))}}><option value="1">Mois en cours</option>{[3,6,12].map(n=><option key={n} value={n}>{n} derniers mois</option>)}<option value="custom">Période personnalisée</option></select></label>{selection==='custom'&&<DateRangeFilter label="Période" from={period.from} to={period.to} onChange={(from,to)=>setPeriod({from,to})}/>}</div>
    <p className="form-hint">Bornes calendaires dans votre fuseau {Intl.DateTimeFormat().resolvedOptions().timeZone}. Contactés et qualifiés : statut actuel des prospects créés sur la période. Conversion : clients liés à ces prospects, à la date de consultation. Répartitions et retards : situation actuelle.</p>
    {error&&<p className="notice notice-error" role="alert">{error} <button className="button" onClick={()=>setRevision(r=>r+1)}>Réessayer</button></p>}{saved&&<p role="status">{saved}</p>}
    {loading?<p role="status">Chargement du reporting…</p>:!error&&overview&&<><div className="metrics-grid">{Object.entries(metrics).map(([key,label])=><div className="metric" key={key}><strong>{key.endsWith('Cents')?money(overview[key]):key==='conversionRate'?overview[key].toFixed(1)+' %':overview[key]}</strong><span>{label}</span></div>)}</div>
    {goal&&<section className="action-group"><h3>Objectif de facturation HT · {goal.month}</h3><p>Objectif : {money(goal.monthlyExclTaxCents)} · Facturé : {money(goal.invoicedExclTaxCents)} HT · Atteinte : {goal.achievementPercent===null?'Non définie (objectif nul)':goal.achievementPercent.toFixed(1)+' %'} · Restant : {money(goal.remainingExclTaxCents)} HT</p><progress max={100} value={Math.min(100,goal.achievementPercent??0)} aria-label="Atteinte de l’objectif de facturation HT"/><form onSubmit={e=>{e.preventDefault();void saveGoal()}} className="form-actions"><label>Objectif mensuel HT (€)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="button" disabled={busy}>Enregistrer l’objectif</button></form><p className="form-hint">Facturation HT, distincte des encaissements. Objectif récurrent conservé côté serveur.</p></section>}
    <div className="report-grid">{(['prospectsCreated','clientsCreated','signedExclTaxCents','invoicedExclTaxCents','receivedInclTaxCents'] as const).map(key=><Chart key={key} title={metrics[key]} monetary={key.endsWith('Cents')} values={monthly.map(m=>({label:m.month,value:m[key]}))}/>)}{pipeline&&<><Chart title="Prospects par statut · situation actuelle" values={pipeline.prospects.map(p=>({label:statusLabels[p.status],value:p._count}))}/><Chart title="Contrats par statut · situation actuelle" values={pipeline.contracts.map(p=>({label:contractLabels[p.status],value:p._count}))}/></>}</div></>}
  </section>
}
